version: 1.{build}

clone_folder: c:\projects\simple-parse
os: Visual Studio 2017
platform: x64
configuration: Release

before_build:
    - echo Running cmake...
    - cd c:\projects\simple-parse
    - cmake -G "Visual Studio 2017 Win64"

test_script:
    - ctest --output-on-failure -C Release
